server:
  port: 80

spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:mysql://localhost:3306/autotrade
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  profiles:
    active: local
    